server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : ${jasypt.encryptor.password}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: kr.flab.tradingmarket.domain
  mapper-locations: classpath:mapper/**/*.xml
spring:
  profiles:
    group:
      "test": testDB,common
      "dev":  devDB,common,awsS3,dev-elasticsearch
      "prod": prodDB,common,awsS3,prod-elasticsearch
chat:
  expiration-date: 14
---
spring:
  config:
    activate:
      on-profile: testDB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: devDB
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(5qoucI8RiWMUi4LqO7ZYO9OL1M7UC/FTRovIWkt1uTbSt82w+AGq6bbbzqX1VyJ1GHcjhZI1xxdkSs3zk7r3519HjtnwkQqjR2tcPTv1aJ8PXJo5WBJUGkfIEdg4SKe+7Gqm8BfeYqg=)
      username: ENC(lbJMtrWTuFYRh/U4fJIp+A==)
      password: ENC(2afjs6pZucLb4spH6Q+dwg==)
    replica:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(lzpPXY5lX1a5Gy81mIkjr2kSH+g3V+F4/vieIDqQ7hqljqh6VdVaG0IoteQ0rjuZU1jXSrkocHtfRQRS+iChutrCVcVh/xMHAgbJxkcTRrkbJtYjG5PuNmH38XlnmoFw/CNUD6w1CDs=)
      username: ENC(6Jvhn/1rIDNC4rM5vz4P+g==)
      password: ENC(FejGmnwZt0Qfr5RMq2rU1w==)
  session:
    storage-type: redis
  redis:
    session:
      cluster:
        nodes: ENC(1CNWiPIofgmPIGLoz/Mzx6mU5hw+7FCypemreVtHCd96eVycxuVIRurcfO/PaViketW2rfeJ/GuwiVjIgzayqMMGnJaBWhAWo0si+7Zmc9yGY9ONS8ZlCK7ZHnXUUuSxLmh27nZOgtLl+NV0KOrQAXGzmXzXBjG1WmxgVc4ZKUCUscJNdqkmlQ==)
        password: ENC(yFzXhCZPRtdlO25IjZlQ1g==)
    chat:
      cluster:
        nodes: ENC(iped5QxnhmByeQ1dFJU9rrsyIuu2t40KcMAwHNNIEeH+7LluHDSO0cVeOAKtlMhdVrDwROw2zRa3TxsW7vkmVLQAq+9WVMt9ToocBSeAKFhfebbYFAqLcC4z5ViDVwRrtLufhCfvhVGWZUHI0f7meVZv5CB1dKIMy+zLNzsuc+KafRnhE/kbAw==)
        password: ENC(yFzXhCZPRtdlO25IjZlQ1g==)
  devtools:
    remote:
      restart:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: prodDB
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ENC(zW2O7Z11WHXkxIP/6QTZvAx2Up7VGneEFYU4K5RGsamYEVtPclvYP8KWT5HIFFQvm+c+G7U9kgvLp/OpyVgR4PkPiBjnftshOqFDebabct49GBiJsPFZZwxGwNWX/4aJ6jBpe4/zhiDnr3SL5HfWdQ==)
      username: ENC(+ShQ99B5HU2QGE/szPbDcg==)
      password: ENC(gxkKsxKpJYB0mASN4HPSXiOS4mC9aEl9)
    replica:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(PEiCBnG5dJVk6RFMlyUOW2qRx8WT9Y4Y2chMsYp/wuPrUtxi3AqtqhCEjsdctoAtm6amv4whi0dryFi6ShJvID8r7JzuJByRYHgNEEnDuBd1PzO1zTVrbW3fkeYzNfgPPV8gcpKRU/B+p6HmdMNpQg==)
      username: ENC(gAWmI5C4FFhU5dmDqBNHcA==)
      password: ENC(CSPqayUrd+GfvDYM/bqJOJd5ru0egiAF)
  session:
    storage-type: redis
  redis:
    session:
      cluster:
        nodes: ENC(EC/V1VeRIj1gAMR9lllrhI83Vf7u5KxksoFxZB95zqBUP+XwOjHnZMJ5TfO6cRFi+azFSSLaVtwl56eLzXH1knT8mUeI/pstGmSJXe0IpaRxN8lDtfdfZmMPAMHUzbFtcRLVIZkMtghqgMrMYu2cxrVHQLX8OUG+ghK1VFrT2dY=)
        password: ENC(iuyFPbotFE+Bc5yyLzfcQw==)
    chat:
      cluster:
        nodes: ENC(mbA7Caf5tYR4XAJRY5NQrIIA27Vt9VAubwg7EOH3lbl8vT3Nwa2t4VcdRXOui0YOCrYwmVWd8N7Ju4rOvJsiMNQMWRhwb5Kb0rlmDqetgTCmBA60qLn5HU1AJt44hynJKhTDsi4XcPeEaZWIRivWx4K6MMaX9cyT2Ap7bTOfh3s=)
        password: ENC(khbn0zgMU6x73NKNGKkAqg==)

---
spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
management:
  endpoints:
    web:
      exposure:
        include: health
---
spring:
  config:
    activate:
      on-profile: awsS3
cloud:
  aws:
    credentials:
      access-key: ENC(R+T4/IelUmO07SrH1mMzzwfZNO3lSeew/KP6nmmCL8Q=)
      secret-key: ENC(56Nn/BmWFnAfgV0s083R/f5A4pXVFM4ZdgaLpIhn6yC0nr6wioRHo1V58OQ0c/eyQ2vI4yfmIjA=)
    s3:
      bucket: ENC(DIOo74eqdLNY1k4lXMv9ag==)
    region: #S3 지역
      static: kr-standard
    stack:
      auto: false
    end-point: ENC(AbYf+7EegWS/kfEDePU9zdufukQRuSyR1S915zwt7I08torE1Sup+JnkyHiUtSNb)
---
spring:
  config:
    activate:
      on-profile: dev-elasticsearch
  elasticsearch:
    host: ENC(QiCeQtd4M+pyIDysa+MUEREUOuxank8h)
    port: ENC(NVQ61tMpz53qcrZr7xKr/g==)
    username: ENC(N9ZPTaD2VIVELs/59tzmOQ==)
    password: ENC(+C3dpfd3xvESjIBSYhoGQMZUHUXNOBtI)
logging:
  level:
    org.elasticsearch.client: TRACE
    org.apache.http: TRACE
    org.springframework.data.elasticsearch.core: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod-elasticsearch
  elasticsearch:
    host: ENC(iJhjqUjiJcwSirI3c16VD1WhVcN5h/h+)
    port: ENC(9ijoTa/Pfb1BxHBnvevAsw==)
    username: ENC(ck7VCbrCGATRJQMOP0WiEQ==)
    password: ENC(ZrExm7rv7of1KTMhUvMwfGgSgSCG5Cir)
